### ISSUE TITLE
Video tutorials?

### ISSUE THREAD

**Issue by liutiming** [wlandau/targets-tutorial#11]
@wlandau thanks so much for this amazing package! Just wondering if there are video tutorials accompanying this repo? What would you suggest to be the way to learn targets, should I start from drake because there are more resources available there? Thanks!

**Comment by wlandau** [comment]
> are video tutorials accompanying this repo?

Not yet, but I recently gave a talk about `targets` at [R/Pharma 2020](https://rinpharma.com/), and I believe the video will eventually be posted to the [R Consortium YouTube channel](https://www.youtube.com/channel/UC_R5smHVXRYGhZYDJsnXTwg/playlists).

> What would you suggest to be the way to learn targets, should I start from drake because there are more resources available there? 

I do not think it is necessary to start with `drake`. With `targets`, I tried to take the approaches that worked and condense them down. I think that's why the overall volume of documentation is lower.

This workshop itself is a good place to start. If you sign up for a free RStudio Cloud account, you can log into https://rstudio.cloud/project/1699460 and work through the numbered R Markdown notebooks with exercises. I designed them to build up familiarity with the concepts and features of `targets`. That's the depth-first approach.

The breadth-first approach is the manual at https://wlandau.github.io/targets-manual, which hopefully is a friendly read as far as user manuals are concerned. Finally, if you just want to hack at it until something clicks, I recommend playing around with the RStudio Cloud spaces linked from the example projects at https://github.com/wlandau/targets-minimal, https://github.com/wlandau/targets-keras, or https://github.com/wlandau/targets-stan,
